<?php
$value = array (
  'wwwprefix' => 'http://localhost',
  'imgprefix' => 'http://localhost',
  'cssprefix' => 'http://localhost',
  'sitename' => '一道乐',
  'sitetitle' => '精品团购每一天',
  'abbreviation' => '一道乐',
  'couponname' => '优惠码',
  'currency' => '￥',
  'currencyname' => 'CNY',
  'timezone' => 'Etc/GMT-8',
  'editor' => 'kind',
  'indexteam' => '0',
  'sideteam' => '0',
  'description' => '',
  'keywords' => '',
  'invitecredit' => '0',
  'conduser' => 0,
  'partnerdown' => 0,
  'gzip' => 0,
  'kefuqq' => '329975604',
  'kefumsn' => '',
  'mobileurl' => '',
  'icp' => '',
  'statcode' => '',
  'sinajiwai' => '',
  'tencentjiwai' => '',
  'kefu_hotline' => '020-123456',
  'server_time' => '9:00-18:00',
  'tousu_email' => '4545565@bn.com',
  'team_share_summary' => '我刚刚免费拿到了一道乐 (www.edaole.com) 去欧洲购物美食的优惠券，真的很便宜啊，快来一起去欧洲血拼吧！',
);
?>